disable_upstream: true

ppxlibs:
  main: "ocaml-ppx/ppxlib#main"
  extras:
    - "patricoferris/ppxlib#refactor-driver-transformer"

ppxes:
  - "janestreet/ppx_sexp_conv#master"
  - url: https://github.com/patricoferris/ppx_deriving_yaml.git
    extras: true
    branches:
      - main

